Feat/clin 2267
Ferlab-Ste-Justine/clin-pipelines-dags pull request #250
Opened 2023-11-10 18:59 UTC by ethienneroy

2023-11-14 16:02 UTC, laurabegin requested changes

2023-11-14 16:02 UTC, laurabegin commented on dags/etl_franklin_check_analysis.py
> +            to_create = {
Rajouter un commentaire qui explique pourquoi no_family c'est une liste mais families c'est un dict?

2023-11-14 16:53 UTC, laurabegin commented on dags/etl_franklin_check_analysis.py
> +        dag_id='etl_import_franklin',
Faut changer le nom du fichier aussi

2023-11-14 16:53 UTC, laurabegin commented on dags/etl_franklin_check_analysis.py
> +                auth()), batch_id()) >> api_sensor >> transfer_from_franklin_to_clin(batch_id(), auth())
Donc là y a plus de tasks qui commencent par un underscore?

2023-11-14 17:02 UTC, ethienneroy commented on dags/etl_franklin_check_analysis.py
> +                auth()), batch_id()) >> api_sensor >> transfer_from_franklin_to_clin(batch_id(), auth())
exact !

2023-11-14 18:33 UTC, laurabegin commented on dags/lib/franklin.py
> +    assay_id = "2765500d-8728-4830-94b5-269c306dbe71"  # value given from franklin
Ça ça va tout le temps être pareil?

2023-11-14 18:48 UTC, ethienneroy commented on dags/lib/franklin.py
> +    assay_id = "2765500d-8728-4830-94b5-269c306dbe71"  # value given from franklin
oui, à moins que le meeting de demain avec Franklin dise autrement

2023-11-14 18:50 UTC, laurabegin approved these changes
Good to me!

2023-11-14 22:15 UTC, creativeyann17 requested changes
Je continue de review demain

2023-11-14 22:15 UTC, creativeyann17 commented on dags/sensors/franklin.py
> +                    all_ready = True
Si la derniere est READY mais celles d'avant ne le sont pas ? c'est plus safe de partir de all_ready = True et le passer a False si au mois une ne l'est pas.

2023-11-14 22:15 UTC, creativeyann17 commented on dags/etl_import_franklin.py
> +            'on_failure_callback': Slack.notify_task_failure,
il manque un `on_success_callback=Slack.notify_dag_completion` quelque part

2023-11-14 22:29 UTC, creativeyann17 commented on dags/lib/franklin.py
> +    conn = http.client.HTTPSConnection("api.genoox.com")
si c'est possible de mettre `"api.genoox.com"` dans config.py, pas forcement dans une var env pour lemoment mais au moins a un seul endroit

2023-11-15 14:07 UTC, ethienneroy commented on dags/sensors/franklin.py
> +                    all_ready = True
non car il break la loop quand dès qu'une False est attrapée donc ce cas décrit arrive seulement si une analyse est créée

2023-11-15 15:38 UTC, ethienneroy commented on dags/lib/franklin.py
> +    assay_id = "2765500d-8728-4830-94b5-269c306dbe71"  # value given from franklin
suite au meeting avec Franklin, on devra modifier ca pour utiliser une variable

2023-11-30 19:23 UTC, merged